global:
  project_dir: !ENV ${OWID_COVID_PROJECT_DIR}
  credentials: !ENV ${OWID_COVID_VAX_CREDENTIALS_FILE}
pipeline:
  get-data:
    parallel: True
    countries:
    njobs: -2
    skip_countries:
      - Colombia
  process-data:
    skip_complete:
    skip_monotonic_check:
      Northern Ireland:
        - date: 2021-04-29
          metrics: people_vaccinated
  generate-dataset: